apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-event-bus-cluster
  namespace: kafka
spec:
  kafka:
    version: 3.6.0
    replicas: 2
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 2
      transaction.state.log.replication.factor: 2
      transaction.state.log.min.isr: 2
    storage:
      type: persistent-claim
      size: 1Gi
  zookeeper:
    replicas: 2
    storage:
      type: persistent-claim
      size: 1Gi
