apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: kafka
spec:
  type: LoadBalancer
  selector:
    strimzi.io/cluster: kafka-event-bus-cluster
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
