apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-storageclass
provisioner: local-volume
volumeBindingMode: WaitForFirstConsumer
parameters:
  reclaimPolicy: Delete


# Volumes:

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume-1
  labels:
    type: local
spec:
  storageClassName: mysql-storageclass
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/shared-vol/scalable-systems/mysql-1"  
  persistentVolumeReclaimPolicy: Delete

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume-2
  labels:
    type: local
spec:
  storageClassName: mysql-storageclass
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/shared-vol/scalable-systems/mysql-2"  
  persistentVolumeReclaimPolicy: Delete

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume-3
  labels:
    type: local
spec:
  storageClassName: mysql-storageclass
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/shared-vol/scalable-systems/mysql-3"  
  persistentVolumeReclaimPolicy: Delete
    
